version: "3.4"

networks:
  default:

services:
  api:
    container_name: tender-api
    build:
      context: .
      dockerfile: deployment/server/Dockerfile
      target: dev
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        RUN_LEVEL: dev
        PYTHON_VERSION: "3.9"
    volumes:
      - .:/opt/app
    ports:
      - "8888:8888"
    restart: unless-stopped
    env_file:
      - .env.local

#  elastic:
#    container_name: tender-elastic
#    image: elasticsearch:8.4.3
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - default
#    volumes:
#      - ./.docker_data/elastic:/usr/share/elasticsearch/data
#
#  redis:
#    container_name: tender-redis
#    image: library/redis:6
#    command: redis-server --appendonly yes
#    ports:
#      - "6379:6379"
#    networks:
#      - default
#    volumes:
#    - ./.docker_data/redis:/var/lib/redis